# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo chmod +x unified.sh
    sudo chmod +x uniform.sh
    sudo chmod +x artifact.sh
- script: |    
    bash uniform.sh
    bash unified.sh
    bash artifact.sh
    
  displayName: 'Run a build script'

- publish: /home/vsts/work/1/s/Anykernel3/UPDATE-AnyKernel3.zip
  artifact: UPDATE-AnyKernel3.zip
